apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: postinstalls.postinstall.openshift.demolab.local
spec:
  group: postinstall.openshift.demolab.local
  names:
    kind: PostInstall
    listKind: PostInstallList
    plural: postinstalls
    singular: postinstall
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1
    served: true
    storage: true
