kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: post-install-operator
subjects:
- kind: ServiceAccount
  name: post-install-operator
  namespace: demolab-post-install-operator  
roleRef:
  kind: ClusterRole
  name: post-install-operator
  apiGroup: rbac.authorization.k8s.io
